### ISSUE TITLE
Unable to Initialize CryptoUtils SDK Using Private Ethereum Key Without MetaMask Dependency

### ISSUE THREAD

**Issue by asynctomatic** [threesigmaxyz/arc-ts-sdk#13]
## Description
The current implementation of the CryptoUtils SDK necessitates the use of MetaMask or a compatible Web3 provider for initialization and transaction signing. This behavior poses limitations when attempting to:

- Recover a private Ethereum key from an external source (e.g., Web3Auth).
- Initialize the CryptoUtils SDK directly using the recovered private key.
- Sign transactions with the private key without invoking MetaMask for user confirmation.

## Current Behavior
Executing the provided TypeScript code yields the following error message:
```ts
import chalk from 'chalk';
import { CryptoUtils, ICryptoUtils } from 'arc-crypto-utils';

(async () => {
  const header = '='.repeat(process.stdout.columns - 1);
  console.log(header);
  console.log(`${chalk.green.bold('Arc Crypto SDK - Local Key Store Example')}`);
  console.log(header);

  try {
    // create custom provider with local key store
    const wallet = {
      privateKey: "0x0123456789012345678901234567890123456789012345678901234567890123",
      providerUrl: "https://eth.merkle.io"
    };

    // init crypto utils
    const cryptoUtils: ICryptoUtils = new CryptoUtils();
    await cryptoUtils.init('some message', wallet);

    process.exit(0);
  
  } catch (ex) {
    const msg = chalk.red(`Error = ${ex}`);
    console.error(msg);
    process.exit(-1);
  }
})();
```
```
Error = Error: could not coalesce error (error={ "code": -32601, "message": "method eth_accounts not available" }, payload={ "id": 2, "jsonrpc": "2.0", "method": "eth_accounts", "params": [ ] }, code=UNKNOWN_ERROR, version=6.7.1)
```

## Expected Behavior
The SDK should offer a pathway for initialization using a private Ethereum key, allowing for transaction signing without MetaMask or a compatible Web3 provider.

## Underlying Issues
- The `init` method in the SDK is designed to obtain the signer from the provider, thereby making assumptions about the presence of MetaMask or a Web3 provider.
- The `getSigner` function expects a public key as an argument, which is incompatible with the desired operation of importing a private key directly.

## Related Code
- `init` method in [CryptoUtils.ts](https://github.com/threesigmaxyz/arc-ts-sdk/blob/91b91ff370526df8cc3437f9ea34feac76970b11/src/packages/crypto/utils/CryptoUtils.ts#L65)
- `getSigner` method in `Signer.ts`

## Proposed Solution
A modification should be made to allow the SDK initialization with a custom signer that accepts a private key as input.

## Acceptance Criteria
- [ ] Support for SDK initialization using a private Ethereum key.
- [ ] Capability to sign transactions without requiring MetaMask user confirmation.

cc: @0x0xyz @JoseAfonsoThreeSigma

**Comment by 0x0xyz** [comment]
The current MR contains the fix: https://github.com/threesigmaxyz/arc-ts-sdk/pull/14
